travis:
  secure:
    BINSTAR_TOKEN: a4egY26J5RDtWki1GZImG7tTYgaeAy1wBhjG17QRYrIfc4HKH4h0iCZp7xdTsUsHsmGKcaoXtN52H7/FkAy3IvIPP79syRoEuWPEOeEiW763pHnlpigTNWlSAjC2vw2vrjK57/604gE5CG5pVRbjYZTGehpNP+xmZjVk8fXkLs4fApO59kxKTN8F/Ou5Kbh5RdhdSHtOg57dcsdzId/oPvRBfVIt8fn7sFWI7EJJWnOBhMb4c/YcJC+7D9JfBMzYYBpcownKy7MbqcLImq3KQQIWQAcwlwDHXAy05FtRnXjQmv6H90co/wDZ/R6WlbUqEP2IuW71AhIbK5fwbHsUpCtYZnUxO615v5qyPiNKZFTqYQrO7krqecvh+INgYQJzfn4tAkIlAiSlX8XkHyakoU3KWQtpfZj0cRYD+4ctZoeaMuLma3WGU0om2TucnVdMp8NL22uSocJn2CqrIkFsCeHKst5XHbi/dNYnB/wbeCqg0y8SC3xTy19ClQN2BkdDdeWXxPwkfQZWfFQ5AjB0gWVZo/j3zwrMDsohI6S8U/uTENThIk66fpyAoAKoCgPl0w9qNB7VfjEy8Nc3VnrvgJAmfrcEYQipBJOx3/noC4OLcfTPEQIlSJA14JdRV4ixJoMMINhKRllZ3fmxIvPHGgC7DOQwXP85NREeAwToYsk=

channels:
  targets:
  - [cryoem, main]
github:
  user_or_org: cryoem
  repo_name: openmpi-feedstock

provider:
  linux: circle
  osx: travis

azure:
  build_id: blank
