travis:
  secure:
    BINSTAR_TOKEN: iCkE4oPGZOm2BICWjslmOICYI6p7JZIE1ZFLs2UIQQpzGZHm5tjXVKjtSSfwsh53vApmBcJ24opZx0Kr13wEN+NSfIBbe2tpN2bwzgbIUshabcwbJrFWwggnqhf8KyFuEw7swRsFnL4ZStmE30F8RIQbnZvYKHUk3QekKF5oee8KPoVkutJLs6KR8C5V9BgKbo5x+bjH68vwscMyyknvTiD2+kSGD3nH1uD7M/Fq7eE54YpdqfblVw8oFNR8NosWsZDe6xdzYPRwkX1MkNaOVlJXMl4QXCeR1aDL0mXS2HUkrUJFbD7GoRK5Vjv0usCdATRaWALpWR3WR/gL7dfyGDGC6TAZYg7WYfNBDkHnizqlPEUBKDkWEu7iemdD6VHONUfhomk1nFpiRfQzXs55MoCtDq1cSoQmv33B+PawKLDN3QNKjTP+GNCJDtpCZEf1vnEn1uT3AIzIveE5fVFKPBbz4+1UGpgC+HZLSbnzqa2Z8BGNvL1RFv+bs3VvxqFALZPod5EqnClcYAtX1ENRaXu2ydl1TwpxVo1Mqcz3dMXhJ3BJWpfWUkGfOulbdJp+J639Ft1YxRD+CI/mZixUV8wbHGypVDzDYVpD5R5rfzIy9KMPb+M3vl1xSjvdp8wOfirc2O/kEqu4qdTnQkdwo2OHxdB1hCBeCngf6b7HmGM=
appveyor:
  secure:
    BINSTAR_TOKEN: OcAUZlpSDgQtX8QAIX7qr8iZhsrOWwlmuyDECE7wAYBRlvXIBJ7BbXhX/Fmz4Oib

channels:
  targets:
  - [cryoem, main]
github:
  user_or_org: cryoem
  repo_name: openmpi-feedstock

provider:
  linux: circle
  osx: travis

azure:
  build_id: blank
